-- ============================================================
-- TLENOR GYM — DATABASE SCHEMA FOR SUPABASE
-- Copiez et exécutez ce script dans le SQL Editor de Supabase
-- ============================================================

-- 1. Table Produits (Compléments Alimentaires)
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    price TEXT NOT NULL,
    description TEXT,
    stock BOOLEAN DEFAULT true,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Table Abonnements & Tarifs
CREATE TABLE IF NOT EXISTS public.plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL, -- 'cardio_muscu' ou 'muscu'
    price TEXT NOT NULL,
    period TEXT NOT NULL,
    features JSONB DEFAULT '[]'::jsonb,
    featured BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Table Demandes & Leads WhatsApp
CREATE TABLE IF NOT EXISTS public.leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT,
    phone TEXT,
    item_type TEXT NOT NULL, -- Produit, Abonnement, Coaching
    status TEXT DEFAULT 'Nouveau', -- Nouveau, Contacté, Validé
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Activez RLS (Row Level Security)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

-- Politiques de lecture publique (Lecture libre pour tous les visiteurs)
CREATE POLICY "Lecture publique produits" ON public.products FOR SELECT USING (true);
CREATE POLICY "Lecture publique tarifs" ON public.plans FOR SELECT USING (true);

-- Politiques d'écriture complète (Insérer / Modifier / Supprimer)
CREATE POLICY "Ecriture produits" ON public.products FOR ALL USING (true);
CREATE POLICY "Ecriture tarifs" ON public.plans FOR ALL USING (true);
CREATE POLICY "Ecriture leads" ON public.leads FOR ALL USING (true);


-- Table prête pour vos vrais produits (À ajouter via l'espace Admin)

