-- ============================================================
-- TLENOR GYM — DATABASE SCHEMA FOR SUPABASE
-- Copiez et exécutez ce script dans le SQL Editor de Supabase
-- ============================================================

-- 1. Table Produits (Compléments Alimentaires)
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    price TEXT NOT NULL,
    description TEXT,
    stock BOOLEAN DEFAULT true,
    stock_quantity INTEGER DEFAULT 10,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Table Abonnements & Tarifs
CREATE TABLE IF NOT EXISTS public.plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL, -- 'cardio_muscu' ou 'muscu'
    price TEXT NOT NULL,
    period TEXT NOT NULL,
    features JSONB DEFAULT '[]'::jsonb,
    featured BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Table Demandes & Leads WhatsApp
CREATE TABLE IF NOT EXISTS public.leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT,
    phone TEXT,
    item_type TEXT NOT NULL, -- Produit, Abonnement, Coaching
    status TEXT DEFAULT 'Nouveau', -- Nouveau, Contacté, Validé
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Table Catégories de produits
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Table pour les commandes de produits (Livraison Algérie / Yalidine)
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    wilaya_code TEXT NOT NULL,
    wilaya_name TEXT NOT NULL,
    commune_name TEXT NOT NULL,
    address TEXT,
    delivery_type TEXT NOT NULL DEFAULT 'home', -- 'home' ou 'office'
    product_name TEXT NOT NULL,
    product_price TEXT NOT NULL,
    delivery_cost NUMERIC DEFAULT 0,
    total_amount NUMERIC NOT NULL,
    status TEXT DEFAULT 'Nouvelle', -- Nouvelle, En cours, Livrée, Annulée
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- RLS (Row Level Security)
-- ============================================================

-- Activez RLS sur toutes les tables
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Politiques de LECTURE et ÉCRITURE publique (pour synchronisation PC / Mobile sans Supabase Auth)
CREATE POLICY "Lecture publique produits" ON public.products FOR SELECT USING (true);
CREATE POLICY "Lecture publique tarifs" ON public.plans FOR SELECT USING (true);
CREATE POLICY "Lecture publique catégories" ON public.categories FOR SELECT USING (true);

-- Ecriture permise pour l'administration et la prise de commande
CREATE POLICY "Ecriture produits" ON public.products FOR ALL USING (true);
CREATE POLICY "Ecriture tarifs" ON public.plans FOR ALL USING (true);
CREATE POLICY "Ecriture catégories" ON public.categories FOR ALL USING (true);
CREATE POLICY "Ecriture commandes" ON public.orders FOR ALL USING (true);
CREATE POLICY "Ecriture leads" ON public.leads FOR ALL USING (true);

-- ============================================================
-- MIGRATION : Si vous avez déjà la base, exécutez ceci :
-- ALTER TABLE public.products ADD COLUMN IF NOT EXISTS stock_quantity INTEGER DEFAULT 10;
-- ============================================================
